//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace User_Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int Job_Id { get; set; }
        public string Job_Position { get; set; }
        public string Job_Description { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Skills { get; set; }
        public Nullable<int> Min_Exp_Req { get; set; }
        public Nullable<int> Max_Exp_Req { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<decimal> PayRate { get; set; }
    }
}
