//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace User_Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Job_Application
    {
        public int Job_Application_Id { get; set; }
        public int Job_Id { get; set; }
        public string Email_Id { get; set; }
    
        public virtual Tbl_Jobs Tbl_Jobs { get; set; }
        public virtual Tbl_Users Tbl_Users { get; set; }
    }
}
