//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace User_Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Users
    {
        public Tbl_Users()
        {
            this.Tbl_Job_Application = new HashSet<Tbl_Job_Application>();
        }
    
        public string Email_Id { get; set; }
        public string User_First_Name { get; set; }
        public string User_Last_Name { get; set; }
        public string User_Street { get; set; }
        public string User_City { get; set; }
        public string User_State { get; set; }
        public string User_Country { get; set; }
        public Nullable<int> Exp_Years { get; set; }
        public string Skills { get; set; }
        public string Resume_Upload { get; set; }
        public int Is_Active { get; set; }
        public string Password { get; set; }
        public string User_Phone_Number { get; set; }
        public string User_Guid { get; set; }
    
        public virtual ICollection<Tbl_Job_Application> Tbl_Job_Application { get; set; }
    }
}
