//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace User_Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Admin
    {
        public string Admin_Email_Id { get; set; }
        public string Admin_First_Name { get; set; }
        public string Admin_Last_Name { get; set; }
        public string Admin_Password { get; set; }
    }
}
